/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package unal.appmenu;

/**
 *
 * @author sebastian
 */
public class frmVoltaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmOhm
     */
    public frmVoltaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCorriente = new javax.swing.JLabel();
        inputCorriente = new javax.swing.JTextField();
        textResistencia = new javax.swing.JLabel();
        inputResistencia = new javax.swing.JTextField();
        textVoltaje = new javax.swing.JLabel();
        inputVoltaje = new javax.swing.JTextField();
        calcularOhm = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Calcular Voltaje");
        setVisible(true);

        textCorriente.setText("Corriente");

        inputCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorrienteActionPerformed(evt);
            }
        });

        textResistencia.setText("Resistencia");

        textVoltaje.setText("Voltaje");

        inputVoltaje.setEnabled(false);
        inputVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVoltajeActionPerformed(evt);
            }
        });

        calcularOhm.setText("Calcular");
        calcularOhm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularOhmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textCorriente)
                    .addComponent(textResistencia)
                    .addComponent(textVoltaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calcularOhm)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCorriente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textResistencia)
                    .addComponent(inputResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textVoltaje)
                    .addComponent(inputVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(calcularOhm)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorrienteActionPerformed

    private void inputVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVoltajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVoltajeActionPerformed

    private void calcularOhmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularOhmActionPerformed
        
        double corriente,resistencia,voltaje;
        corriente=Double.parseDouble(inputCorriente.getText());
        resistencia=Double.parseDouble(inputResistencia.getText());
        
        voltaje=corriente*resistencia;
        inputVoltaje.setText(String.valueOf(voltaje));
    }//GEN-LAST:event_calcularOhmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularOhm;
    private javax.swing.JTextField inputCorriente;
    private javax.swing.JTextField inputResistencia;
    private javax.swing.JTextField inputVoltaje;
    private javax.swing.JLabel textCorriente;
    private javax.swing.JLabel textResistencia;
    private javax.swing.JLabel textVoltaje;
    // End of variables declaration//GEN-END:variables
}
