/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package unal.appmenu;

/**
 *
 * @author sebastian
 */
public class frmCorriente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCorriente
     */
    public frmCorriente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textResistencia = new javax.swing.JLabel();
        inputResistencia = new javax.swing.JTextField();
        textVoltaje = new javax.swing.JLabel();
        inputVoltaje = new javax.swing.JTextField();
        textCorriente = new javax.swing.JLabel();
        inputCorriente = new javax.swing.JTextField();
        calcularOhm = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Calcular Corriente");

        textResistencia.setText("Resistencia");

        textVoltaje.setText("Voltaje");

        inputVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVoltajeActionPerformed(evt);
            }
        });

        textCorriente.setText("Corriente");

        inputCorriente.setEnabled(false);
        inputCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorrienteActionPerformed(evt);
            }
        });

        calcularOhm.setText("Calcular");
        calcularOhm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularOhmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textResistencia)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textVoltaje)
                                .addComponent(textCorriente)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(calcularOhm))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(inputResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textResistencia)
                    .addComponent(inputResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textVoltaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCorriente)
                    .addComponent(inputCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(calcularOhm)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularOhmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularOhmActionPerformed

        double corriente,resistencia,voltaje;
        voltaje=Double.parseDouble(inputVoltaje.getText());
        resistencia=Double.parseDouble(inputResistencia.getText());

        corriente=voltaje/resistencia;
        inputCorriente.setText(String.valueOf(corriente));
    }//GEN-LAST:event_calcularOhmActionPerformed

    private void inputCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorrienteActionPerformed

    private void inputVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVoltajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVoltajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularOhm;
    private javax.swing.JTextField inputCorriente;
    private javax.swing.JTextField inputResistencia;
    private javax.swing.JTextField inputVoltaje;
    private javax.swing.JLabel textCorriente;
    private javax.swing.JLabel textResistencia;
    private javax.swing.JLabel textVoltaje;
    // End of variables declaration//GEN-END:variables
}
